---

- name: Install caddy subconfigs
  template:
    src: "{{ item.template }}"
    dest: "/etc/caddy/conf.d/{% if item.target_filename is defined %}{{ item.target_filename }}{% else %}{{ item.template | basename | regex_replace('\\.(j2|jinja2?)$', '') }}{% endif %}"
    owner: caddy
    group: caddy
    mode: 0600
  loop: "{{ caddy_subconfigs }}"
  notify:
    - Regenerate caddy config
    - Reload caddy
