---

- name: Install updater dependencies
  package:
    name:
      - jq

- name: Create user caddy
  user:
    name: caddy
    shell: /usr/bin/nologin

- name: Create necessary directory structure
  file:
    path: "/home/caddy/{{ item }}"
    state: directory
    mode: 0755
    owner: caddy
    group: caddy
  loop:
    - .local
    - .local/bin

- name: Install caddy config generator
  copy:
    src: generate_caddy_config.sh
    dest: /home/caddy/.local/bin
    owner: caddy
    group: caddy
    mode: 0700

- name: Install caddy service
  copy:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: 0644
  notify: Restart caddy

- name: Deploy caddy updater script
  template:
    src: update_caddy.sh.j2
    dest: /home/caddy/.local/bin/update_caddy.sh
    owner: caddy
    group: caddy
    mode: 0700
  register: caddy_update_deploy

- name: Allow user caddy to restart caddy
  community.general.sudoers:
    name: allow-restart-caddy
    state: present
    user: caddy
    commands: /bin/systemctl restart caddy

- name: Install caddy via updater
  become: yes
  become_user: caddy
  command:
    cmd: /home/caddy/.local/bin/update_caddy.sh -f
    creates: "{% if caddy_update_deploy.changed %}/this_does_never_exist{% else %}/home/caddy/.local/bin/caddy{% endif %}"
  ignore_errors: "{{ ansible_check_mode }}"
  # No notify, the updater script restarts the service itself

- name: Setup timed systemd update job
  include_role:
    name: systemd
  vars:
    systemd_name: caddy-updater
    systemd_script_owner: caddy
    systemd_script_group: caddy
    systemd_service_description: Update caddy to newest version
    systemd_service_options:
      ExecStart: /home/caddy/.local/bin/update_caddy.sh
      User: caddy
      Group: caddy
    systemd_notify:
      failed: true
      success: true
    systemd_timer_description: "Try to update caddy once per day sometime between 5:00 and 6:00"
    systemd_timer_options:
      OnCalendar: "*-*-* 05:00"
      RandomizedDelaySec: 3600

- name: Create caddy config directory
  file:
    path: /etc/caddy
    owner: caddy
    group: caddy
    mode: 0700
    state: directory
  notify: Reload caddy

- name: Install caddy main config
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: 0600
  notify: Reload caddy

- name: Create the webroot
  file:
    path: "{{ caddy_webroot }}"
    state: directory
    owner: caddy
    group: caddy
    mode: 0755

- name: Create the log directory
  file:
    path: "{{ caddy_logdir }}"
    state: directory
    owner: caddy
    group: caddy
    mode: 0711
  notify: Restart caddy

- name: Enable caddy
  service:
    name: caddy
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install global directive files provided by caller
  include_tasks: add_global_directive_config.yml
  loop: "{{ lookup('community.general.merge_variables', 'caddy_global_directive_configs', pattern_type='prefix') | default([], true) }}"
  loop_control:
    loop_var: caddy_global_directive_config
    label: "{{ caddy_global_directive_config.template }}"
  when: lookup('ansible.builtin.varnames', 'caddy_global_directive_configs')

- name: Install caddy site configs provided by caller
  include_tasks: add_site_config.yml
  loop: "{{ lookup('community.general.merge_variables', 'caddy_site_configs', pattern_type='prefix') | default([], true) }}"
  loop_control:
    loop_var: caddy_site_config
    label: "{{ caddy_site_config.template }}"
  when: lookup('ansible.builtin.varnames', 'caddy_site_configs')

- name: Install caddy subconfigs provided by caller
  include_tasks: add_generic_subconfig.yml
  loop: "{{ lookup('community.general.merge_variables', 'caddy_subconfigs', pattern_type='prefix') | default([], true) }}"
  loop_control:
    loop_var: caddy_generic_subconfig
    label: "{{ caddy_generic_subconfig.template }}"
  when: lookup('ansible.builtin.varnames', 'caddy_subconfigs')
